export const EXPERIENCE_ERROR_CODES = Object.freeze({
  CHANNEL_NOT_SUPPORTED: 'EXPERIENCE_CHANNEL_NOT_SUPPORTED',
  RENDERING_NOT_SUPPORTED: 'EXPERIENCE_RENDERING_NOT_SUPPORTED',
  INVALID_REQUEST: 'EXPERIENCE_INVALID_REQUEST'
});
