import assert from 'node:assert/strict';
import test from 'node:test';
import { PlatformError } from '../../src/foundation/index.js';
import { FINANCIAL_OPERATIONS_GOVERNANCE_ASSURANCE_ERROR_CODE, FinancialOperationsGovernanceAssuranceDescriptor as Descriptor, FinancialOperationsGovernanceAssuranceProfile as Profile } from '../../src/pricing-billing-payments/index.js';
const keys = ['operatingRoles', 'serviceObjectives', 'telemetryFields', 'fraudBoundaries', 'incidentClasses', 'recoveryEvidence', 'governanceArtifacts', 'assuranceActivities', 'invariants'];
const complete = descriptor => { const values = {}; for (const key of keys) values[key] = descriptor[key](); return new Profile({ profileName: 'Financial operations', ...values }); };
test('ARCH-026-09 exposes ownership objectives telemetry fraud incidents recovery governance and assurance', () => { const descriptor = new Descriptor(); assert.ok(descriptor.operatingRoles().includes('financial-control-owner')); assert.ok(descriptor.serviceObjectives().includes('reconciliation-completion-variance')); assert.ok(descriptor.fraudBoundaries().includes('fraud-models-do-not-own-financial-state')); assert.ok(descriptor.incidentClasses().includes('payment-token-boundary-breach')); assert.ok(descriptor.assuranceActivities().includes('architecture-conformance-tests')); });
test('ARCH-026-09 validates operational and fraud safeguards', () => { const descriptor = new Descriptor(); assert.equal(descriptor.validateProfile(complete(descriptor)).isValid, true); const result = descriptor.validateProfile({ fraudModelOwnsFinancialState: true, protectedPayloadsCopiedToTelemetry: true, controlsBypassedUnderPressure: true }); assert.equal(result.isValid, false); assert.match(result.errors.join('\n'), /fraud models owning financial state/); assert.match(result.errors.join('\n'), /protected payloads in telemetry/); assert.match(result.errors.join('\n'), /bypassing controls under pressure/); });
test('ARCH-026-09 detects incomplete metadata and preserves immutability', () => { class Incomplete extends Descriptor { assuranceActivities() { return []; } } assert.throws(() => new Incomplete().assertArchitecture(), error => error instanceof PlatformError && error.code === FINANCIAL_OPERATIONS_GOVERNANCE_ASSURANCE_ERROR_CODE); assert.throws(() => complete(new Descriptor()).operatingRoles.push('x'), TypeError); });
