export const GATEWAY_ERROR_CODES = Object.freeze({
  AUTHENTICATION_FAILED: 'GATEWAY_AUTHENTICATION_FAILED',
  AUTHORIZATION_FAILED: 'GATEWAY_AUTHORIZATION_FAILED',
  RATE_LIMIT_EXCEEDED: 'GATEWAY_RATE_LIMIT_EXCEEDED',
  VALIDATION_FAILED: 'GATEWAY_VALIDATION_FAILED',
  ROUTING_FAILED: 'GATEWAY_ROUTING_FAILED'
});
