export const PLATFORM_NAME = 'XeniosAI';

export const DEFAULT_LOG_LEVEL = 'info';

export const ERROR_CODES = Object.freeze({
  CONFIGURATION_MISSING: 'FOUNDATION_CONFIGURATION_MISSING',
  FEATURE_FLAG_MISSING: 'FOUNDATION_FEATURE_FLAG_MISSING',
  SECRET_MISSING: 'FOUNDATION_SECRET_MISSING',
  SERVICE_NOT_REGISTERED: 'FOUNDATION_SERVICE_NOT_REGISTERED',
  SERVICE_ALREADY_REGISTERED: 'FOUNDATION_SERVICE_ALREADY_REGISTERED',
  INVALID_ARGUMENT: 'FOUNDATION_INVALID_ARGUMENT'
});
