export const SERVICE_CATEGORY_NAMES = Object.freeze({
  HOSPITALITY_OPERATIONS: 'hospitality-operations',
  KNOWLEDGE_MANAGEMENT: 'knowledge-management',
  PROPERTY_MANAGEMENT: 'property-management',
  PLATFORM_SERVICES: 'platform-services',
  BUSINESS_INTELLIGENCE: 'business-intelligence'
});

export const SERVICE_LIFECYCLE_STAGES = Object.freeze({
  PROPOSAL: 'proposal',
  CONCEPT: 'concept',
  ARCHITECTURE: 'architecture',
  IMPLEMENTATION: 'implementation',
  TESTING: 'testing',
  DEPLOYMENT: 'deployment',
  OPERATION: 'operation',
  EVOLUTION: 'evolution',
  DEPRECATION: 'deprecation',
  RETIREMENT: 'retirement'
});

export const SERVICE_LIFECYCLE_CHECKPOINTS = Object.freeze({
  PROPOSAL_APPROVAL: 'proposal-approval',
  ARCHITECTURE_REVIEW: 'architecture-review',
  PRODUCTION_READINESS_REVIEW: 'production-readiness-review',
  DEPRECATION_APPROVAL: 'deprecation-approval',
  RETIREMENT_APPROVAL: 'retirement-approval'
});

export const SERVICE_DEPENDENCY_TYPES = Object.freeze({
  FUNCTIONAL: 'functional',
  INFORMATIONAL: 'informational',
  OPERATIONAL: 'operational',
  INFRASTRUCTURE: 'infrastructure'
});

export const EXTERNAL_SERVICE_DEPENDENCIES = Object.freeze({
  INTEGRATION_LAYER: 'integration-layer',
  OBJECT_STORAGE: 'object-storage'
});

export const EXTERNAL_COLLABORATORS = Object.freeze({
  AI_INTELLIGENCE_LAYER: 'ai-intelligence-layer',
  GATEWAY_LAYER: 'gateway-layer',
  INTEGRATION_LAYER: 'integration-layer',
  ALL_OPERATIONAL_SERVICES: 'all-operational-services'
});

export const SERVICE_COMMUNICATION_PATTERNS = Object.freeze({
  QUERY: 'query',
  COMMAND: 'command',
  DOMAIN_EVENT: 'domain-event',
  WORKFLOW_ORCHESTRATION: 'workflow-orchestration'
});

export const COMMUNICATION_SURFACES = Object.freeze({
  PUBLIC_CONTRACT: 'public-contract',
  INTERNAL_API: 'internal-api',
  SHARED_DATABASE: 'shared-database',
  SHARED_INTERNAL_MODEL: 'shared-internal-model'
});

export const VERSIONED_ARTIFACT_TYPES = Object.freeze({
  SERVICE: 'service',
  PUBLIC_API: 'public-api',
  COMMAND: 'command',
  QUERY: 'query',
  DOMAIN_EVENT: 'domain-event',
  SHARED_SCHEMA: 'shared-schema',
  TOOL_CONTRACT: 'tool-contract',
  CONFIGURATION_FORMAT: 'configuration-format'
});

export const VERSION_CHANGE_TYPES = Object.freeze({
  BREAKING: 'breaking',
  FEATURE: 'feature',
  FIX: 'fix'
});

export const SERVICE_MAP_ERROR_CODES = Object.freeze({
  SERVICE_NOT_FOUND: 'SERVICE_MAP_SERVICE_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'SERVICE_MAP_CATEGORY_NOT_FOUND',
  DUPLICATE_SERVICE: 'SERVICE_MAP_DUPLICATE_SERVICE',
  CATALOG_ENTRY_NOT_FOUND: 'SERVICE_MAP_CATALOG_ENTRY_NOT_FOUND',
  DUPLICATE_CATALOG_ENTRY: 'SERVICE_MAP_DUPLICATE_CATALOG_ENTRY',
  CAPABILITY_OWNER_NOT_FOUND: 'SERVICE_MAP_CAPABILITY_OWNER_NOT_FOUND',
  DUPLICATE_CAPABILITY_OWNER: 'SERVICE_MAP_DUPLICATE_CAPABILITY_OWNER',
  OWNERSHIP_VIOLATION: 'SERVICE_MAP_OWNERSHIP_VIOLATION',
  DUPLICATE_SERVICE_DEPENDENCY: 'SERVICE_MAP_DUPLICATE_SERVICE_DEPENDENCY',
  SERVICE_DEPENDENCY_NOT_FOUND: 'SERVICE_MAP_SERVICE_DEPENDENCY_NOT_FOUND',
  SERVICE_DEPENDENCY_NOT_ALLOWED: 'SERVICE_MAP_SERVICE_DEPENDENCY_NOT_ALLOWED',
  CIRCULAR_SERVICE_DEPENDENCY: 'SERVICE_MAP_CIRCULAR_SERVICE_DEPENDENCY',
  SERVICE_BOUNDARY_NOT_FOUND: 'SERVICE_MAP_SERVICE_BOUNDARY_NOT_FOUND',
  DUPLICATE_SERVICE_BOUNDARY: 'SERVICE_MAP_DUPLICATE_SERVICE_BOUNDARY',
  SERVICE_BOUNDARY_VIOLATION: 'SERVICE_MAP_SERVICE_BOUNDARY_VIOLATION',
  COMMUNICATION_CONTRACT_NOT_FOUND: 'SERVICE_MAP_COMMUNICATION_CONTRACT_NOT_FOUND',
  DUPLICATE_COMMUNICATION_CONTRACT: 'SERVICE_MAP_DUPLICATE_COMMUNICATION_CONTRACT',
  COMMUNICATION_PATTERN_NOT_ALLOWED: 'SERVICE_MAP_COMMUNICATION_PATTERN_NOT_ALLOWED',
  COMMUNICATION_CONTRACT_INVALID: 'SERVICE_MAP_COMMUNICATION_CONTRACT_INVALID',
  COMMUNICATION_ANTI_PATTERN: 'SERVICE_MAP_COMMUNICATION_ANTI_PATTERN',
  SERVICE_LIFECYCLE_RECORD_NOT_FOUND: 'SERVICE_MAP_LIFECYCLE_RECORD_NOT_FOUND',
  DUPLICATE_SERVICE_LIFECYCLE_RECORD: 'SERVICE_MAP_DUPLICATE_LIFECYCLE_RECORD',
  SERVICE_LIFECYCLE_OWNER_MISSING: 'SERVICE_MAP_LIFECYCLE_OWNER_MISSING',
  SERVICE_LIFECYCLE_TRANSITION_INVALID: 'SERVICE_MAP_LIFECYCLE_TRANSITION_INVALID',
  SERVICE_LIFECYCLE_REQUIREMENT_MISSING: 'SERVICE_MAP_LIFECYCLE_REQUIREMENT_MISSING',
  VERSION_RECORD_NOT_FOUND: 'SERVICE_MAP_VERSION_RECORD_NOT_FOUND',
  DUPLICATE_VERSION_RECORD: 'SERVICE_MAP_DUPLICATE_VERSION_RECORD',
  VERSION_INVALID: 'SERVICE_MAP_VERSION_INVALID',
  VERSION_CHANGE_INVALID: 'SERVICE_MAP_VERSION_CHANGE_INVALID',
  VERSION_DEPRECATION_INVALID: 'SERVICE_MAP_VERSION_DEPRECATION_INVALID'
});
