export const SERVICE_CATEGORY_NAMES = Object.freeze({
  HOSPITALITY_OPERATIONS: 'hospitality-operations',
  KNOWLEDGE_MANAGEMENT: 'knowledge-management',
  PROPERTY_MANAGEMENT: 'property-management',
  PLATFORM_SERVICES: 'platform-services',
  BUSINESS_INTELLIGENCE: 'business-intelligence'
});

export const SERVICE_LIFECYCLE_STAGES = Object.freeze({
  CONCEPT: 'concept',
  ARCHITECTURE: 'architecture',
  IMPLEMENTATION: 'implementation',
  DEPLOYMENT: 'deployment',
  OPERATION: 'operation',
  EVOLUTION: 'evolution',
  RETIREMENT: 'retirement'
});

export const SERVICE_DEPENDENCY_TYPES = Object.freeze({
  FUNCTIONAL: 'functional',
  INFORMATIONAL: 'informational',
  OPERATIONAL: 'operational',
  INFRASTRUCTURE: 'infrastructure'
});

export const EXTERNAL_SERVICE_DEPENDENCIES = Object.freeze({
  INTEGRATION_LAYER: 'integration-layer',
  OBJECT_STORAGE: 'object-storage'
});

export const SERVICE_MAP_ERROR_CODES = Object.freeze({
  SERVICE_NOT_FOUND: 'SERVICE_MAP_SERVICE_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'SERVICE_MAP_CATEGORY_NOT_FOUND',
  DUPLICATE_SERVICE: 'SERVICE_MAP_DUPLICATE_SERVICE',
  CATALOG_ENTRY_NOT_FOUND: 'SERVICE_MAP_CATALOG_ENTRY_NOT_FOUND',
  DUPLICATE_CATALOG_ENTRY: 'SERVICE_MAP_DUPLICATE_CATALOG_ENTRY',
  CAPABILITY_OWNER_NOT_FOUND: 'SERVICE_MAP_CAPABILITY_OWNER_NOT_FOUND',
  DUPLICATE_CAPABILITY_OWNER: 'SERVICE_MAP_DUPLICATE_CAPABILITY_OWNER',
  OWNERSHIP_VIOLATION: 'SERVICE_MAP_OWNERSHIP_VIOLATION',
  DUPLICATE_SERVICE_DEPENDENCY: 'SERVICE_MAP_DUPLICATE_SERVICE_DEPENDENCY',
  SERVICE_DEPENDENCY_NOT_FOUND: 'SERVICE_MAP_SERVICE_DEPENDENCY_NOT_FOUND',
  SERVICE_DEPENDENCY_NOT_ALLOWED: 'SERVICE_MAP_SERVICE_DEPENDENCY_NOT_ALLOWED',
  CIRCULAR_SERVICE_DEPENDENCY: 'SERVICE_MAP_CIRCULAR_SERVICE_DEPENDENCY'
});
