import assert from 'node:assert/strict';
import test from 'node:test';
import { PlatformError, ServiceCollection } from '../../src/foundation/index.js';
import { DELIVERY_REFERENCE_ARCHITECTURAL_RULES, DELIVERY_TESTING_AND_CONFORMANCE_REFERENCE_ERROR_CODE, DeliveryTestingAndConformanceReferenceDescriptor, DeliveryTestingAndConformanceReferenceProfile, addReferenceImplementations } from '../../src/reference-implementations/index.js';
const METADATA_KEYS = ['goldenPathCapabilities', 'environmentSeparationDimensions', 'deliveryPipelineStages', 'testPyramidLevels', 'contractTestCoverage', 'aiEvaluationGates', 'workflowTestControls', 'securityTestAreas', 'performanceCapacityDimensions', 'releaseStrategyControls', 'conformanceReportFields', 'productionizationChecklistAreas', 'referenceAcceptanceCriteria', 'architecturalRules'];
test('ARCH-020-09 exposes golden-path, environment, pipeline, and test-pyramid metadata', () => { const descriptor = new DeliveryTestingAndConformanceReferenceDescriptor(); assert.ok(descriptor.goldenPathCapabilities().includes('tenant-context-libraries')); assert.ok(descriptor.environmentSeparationDimensions().includes('resilience')); assert.ok(descriptor.deliveryPipelineStages().includes('approve-and-progressively-release')); assert.ok(descriptor.testPyramidLevels().includes('security-and-tenant-isolation-tests')); });
test('ARCH-020-09 exposes contract, AI, workflow, security, and capacity metadata', () => { const descriptor = new DeliveryTestingAndConformanceReferenceDescriptor(); assert.ok(descriptor.contractTestCoverage().includes('idempotency')); assert.ok(descriptor.aiEvaluationGates().includes('unsafe-action')); assert.ok(descriptor.workflowTestControls().includes('deterministic-clocks')); assert.ok(descriptor.securityTestAreas().includes('ai-prompt-injection')); assert.ok(descriptor.performanceCapacityDimensions().includes('fairness')); });
test('ARCH-020-09 exposes release, conformance, productionization, and architectural metadata', () => { const descriptor = new DeliveryTestingAndConformanceReferenceDescriptor(); assert.ok(descriptor.releaseStrategyControls().includes('canary-or-cohort-rollout')); assert.ok(descriptor.conformanceReportFields().includes('expiry-or-rerun-triggers')); assert.ok(descriptor.productionizationChecklistAreas().includes('rollback-and-exit')); assert.ok(descriptor.architecturalRules().includes(DELIVERY_REFERENCE_ARCHITECTURAL_RULES.AI_EVALUATION_IS_A_RELEASE_CONTROL)); });
test('ARCH-020-09 validates profiles and rejects delivery-control shortcuts', () => { const descriptor = new DeliveryTestingAndConformanceReferenceDescriptor(); assert.equal(descriptor.validateProfile(complete(descriptor)).isValid, true); const validation = descriptor.validateProfile({ buildsAreReproducibleOrAttestable: false, untrackedSourceChangesArePromoted: true, failedConformanceChecksCanBeBypassed: true, modelChangesAvoidTargetedAndRegressionEvaluation: true, productionPromotionUsesMutableArtifacts: true }); assert.equal(validation.isValid, false); assert.match(validation.errors.join('\n'), /must have a name/); assert.match(validation.errors.join('\n'), /reproducible or attestable/); assert.match(validation.errors.join('\n'), /untracked source changes/); assert.match(validation.errors.join('\n'), /bypassing failed conformance checks/); assert.match(validation.errors.join('\n'), /targeted and regression evaluation/); assert.match(validation.errors.join('\n'), /mutable artifacts/); });
test('ARCH-020-09 detects incomplete delivery testing and conformance metadata', () => { class IncompleteDescriptor extends DeliveryTestingAndConformanceReferenceDescriptor { conformanceReportFields() { return []; } } assert.throws(() => new IncompleteDescriptor().assertArchitecture(), (error) => error instanceof PlatformError && error.code === DELIVERY_TESTING_AND_CONFORMANCE_REFERENCE_ERROR_CODE); });
test('ARCH-020-09 profile is immutable and descriptor is registered', () => { const descriptor = addReferenceImplementations(new ServiceCollection()).buildServiceProvider().getRequiredService('DeliveryTestingAndConformanceReferenceDescriptor'); assert.ok(descriptor instanceof DeliveryTestingAndConformanceReferenceDescriptor); assert.equal(descriptor.assertArchitecture().isValid, true); const profile = complete(descriptor); assert.ok(Object.isFrozen(profile)); assert.throws(() => profile.deliveryPipelineStages.push('other'), TypeError); });
function complete(descriptor) { const metadata = {}; for (const key of METADATA_KEYS) metadata[key] = descriptor[key](); return new DeliveryTestingAndConformanceReferenceProfile({ referenceName: 'Delivery, Testing, and Conformance Reference', ...metadata }); }
