import assert from 'node:assert/strict'; import test from 'node:test';
import { PlatformError, ServiceCollection } from '../../src/foundation/index.js';
import { FUTURE_REFERENCE_ARCHITECTURAL_RULES, FUTURE_REFERENCE_IMPLEMENTATION_EVOLUTION_ERROR_CODE, FutureReferenceImplementationEvolutionDescriptor, FutureReferenceImplementationEvolutionProfile, addReferenceImplementations } from '../../src/reference-implementations/index.js';
const KEYS = ['evolutionPrinciples', 'evolutionHorizons', 'additionalVerticals', 'technologyVariantDimensions', 'executableArchitectureArtifacts', 'aiAssistedImplementationOutputs', 'aiOutputProvenance', 'simulationScenarios', 'certificationComponents', 'ecosystemReferenceControls', 'continuousConformanceSignals', 'portfolioGovernanceFactors', 'referenceAcceptanceCriteria', 'architecturalRules'];
test('ARCH-020-10 exposes evolution, vertical, variant, executable architecture, and AI provenance metadata', () => { const d = new FutureReferenceImplementationEvolutionDescriptor(); assert.ok(d.evolutionHorizons().includes('certified-ecosystem-references')); assert.ok(d.additionalVerticals().includes('loyalty-and-guest-engagement')); assert.ok(d.technologyVariantDimensions().includes('identical-conformance-tests')); assert.ok(d.executableArchitectureArtifacts().includes('conformance-profiles')); assert.ok(d.aiOutputProvenance().includes('reviewer')); });
test('ARCH-020-10 exposes simulation, certification, ecosystem, continuous conformance, governance, and rules', () => { const d = new FutureReferenceImplementationEvolutionDescriptor(); assert.ok(d.simulationScenarios().includes('regional-outages')); assert.ok(d.certificationComponents().includes('scoring-thresholds')); assert.ok(d.ecosystemReferenceControls().includes('tenant-consent')); assert.ok(d.continuousConformanceSignals().includes('expired-evidence')); assert.ok(d.portfolioGovernanceFactors().includes('funded-lifecycle-ownership')); assert.ok(d.architecturalRules().includes(FUTURE_REFERENCE_ARCHITECTURAL_RULES.CERTIFICATION_IS_SCOPED_AND_EXPIRING)); });
test('ARCH-020-10 validates profiles and rejects evolution shortcuts', () => { const d = new FutureReferenceImplementationEvolutionDescriptor(); assert.equal(d.validateProfile(complete(d)).isValid, true); const v = d.validateProfile({ variantsPassTheSameProfile: false, generatedArtifactsAreUnreviewed: true, marketplaceStatusEqualsConformanceCertification: true, staleReferencesRemainPresentedAsCurrent: true, certificationCreatesPermanentTrust: true }); assert.equal(v.isValid, false); assert.match(v.errors.join('\n'), /must have a name/); assert.match(v.errors.join('\n'), /same profile/); assert.match(v.errors.join('\n'), /unreviewed generated artifacts/); assert.match(v.errors.join('\n'), /marketplace status/); assert.match(v.errors.join('\n'), /stale references/); assert.match(v.errors.join('\n'), /permanent trust/); });
test('ARCH-020-10 detects incomplete future evolution metadata', () => { class Incomplete extends FutureReferenceImplementationEvolutionDescriptor { certificationComponents() { return []; } } assert.throws(() => new Incomplete().assertArchitecture(), (e) => e instanceof PlatformError && e.code === FUTURE_REFERENCE_IMPLEMENTATION_EVOLUTION_ERROR_CODE); });
test('ARCH-020-10 profile is immutable and descriptor is registered', () => { const d = addReferenceImplementations(new ServiceCollection()).buildServiceProvider().getRequiredService('FutureReferenceImplementationEvolutionDescriptor'); assert.ok(d instanceof FutureReferenceImplementationEvolutionDescriptor); assert.equal(d.assertArchitecture().isValid, true); const p = complete(d); assert.ok(Object.isFrozen(p)); assert.throws(() => p.evolutionPrinciples.push('other'), TypeError); });
function complete(d) { const metadata = {}; for (const key of KEYS) metadata[key] = d[key](); return new FutureReferenceImplementationEvolutionProfile({ referenceName: 'Future Reference Implementation Evolution', ...metadata }); }
