export const PLATFORM_LAYERS = Object.freeze({
  FOUNDATION: 'foundation',
  EXPERIENCE: 'experience',
  GATEWAY: 'gateway',
  CONVERSATION: 'conversation',
  AI_INTELLIGENCE: 'ai-intelligence',
  BUSINESS_SERVICES: 'business-services',
  DATA: 'data',
  INTEGRATION: 'integration',
  EXTERNAL_PROVIDERS: 'external-providers'
});

export const INTERACTION_STYLES = Object.freeze({
  REQUEST_RESPONSE: 'request-response',
  COMMAND: 'command',
  QUERY: 'query',
  DOMAIN_EVENT: 'domain-event'
});

export const INTERACTION_ERROR_CODES = Object.freeze({
  INVALID_LAYER: 'INTERACTION_INVALID_LAYER',
  FORBIDDEN_INTERACTION: 'INTERACTION_FORBIDDEN',
  INVALID_TRAVERSAL: 'INTERACTION_INVALID_TRAVERSAL'
});

export const CANONICAL_REQUEST_FLOW = Object.freeze([
  PLATFORM_LAYERS.EXPERIENCE,
  PLATFORM_LAYERS.GATEWAY,
  PLATFORM_LAYERS.CONVERSATION,
  PLATFORM_LAYERS.AI_INTELLIGENCE,
  PLATFORM_LAYERS.BUSINESS_SERVICES,
  PLATFORM_LAYERS.DATA,
  PLATFORM_LAYERS.INTEGRATION,
  PLATFORM_LAYERS.BUSINESS_SERVICES,
  PLATFORM_LAYERS.AI_INTELLIGENCE,
  PLATFORM_LAYERS.CONVERSATION,
  PLATFORM_LAYERS.EXPERIENCE
]);

export const DEPENDENCY_DIRECTION = Object.freeze([
  PLATFORM_LAYERS.EXPERIENCE,
  PLATFORM_LAYERS.GATEWAY,
  PLATFORM_LAYERS.CONVERSATION,
  PLATFORM_LAYERS.AI_INTELLIGENCE,
  PLATFORM_LAYERS.BUSINESS_SERVICES,
  PLATFORM_LAYERS.DATA
]);
