flowchart LR

    A[Business Service]

    A --> B[Business Event]

    B --> C[Messaging Infrastructure]

    C --> D[Consumer Service]

    D --> E[Business Processing]

    E --> F[Business Outcome]