import assert from 'node:assert/strict';
import test from 'node:test';
import { PlatformError, ServiceCollection } from '../../src/foundation/index.js';
import {
  WORKFLOW_AGENT_RESULT_FIELDS, WORKFLOW_AGENT_TASK_TYPES, WORKFLOW_CORRELATION_CARDINALITIES,
  WORKFLOW_DECISION_CONTRACT_FIELDS, WORKFLOW_EVENT_ACCEPTANCE_OUTCOMES, WORKFLOW_EVENT_ARRIVAL_POLICIES,
  WORKFLOW_EVENT_CONTRACT_FIELDS, WORKFLOW_EVENT_WAIT_FIELDS, WORKFLOW_HUMAN_ASSIGNMENT_TARGETS,
  WORKFLOW_HUMAN_TASK_STATES, WORKFLOW_INTERACTION_BOUNDARIES, WORKFLOW_INTERACTION_ERROR_CODE,
  WORKFLOW_INTERACTION_OPERATIONS, WORKFLOW_INTERACTION_QUALITY_ATTRIBUTES, WORKFLOW_INTERACTION_RULES,
  WORKFLOW_INTERACTION_TYPES, WORKFLOW_MULTI_PERSON_DECISIONS, WORKFLOW_TIMER_FIELDS,
  WORKFLOW_TIMER_MISFIRE_POLICIES, WORKFLOW_TIMER_TYPES,
  WorkflowInteractionDescriptor, WorkflowInteractionProfile, addWorkflowEngine
} from '../../src/workflow-engine/index.js';
test('ARCH-015-05 exposes event contracts, outcomes, waits, correlation, and arrival policies',()=>{const d=new WorkflowInteractionDescriptor();assert.deepEqual(d.interactionTypes(),Object.values(WORKFLOW_INTERACTION_TYPES));assert.ok(d.eventContractFields().includes(WORKFLOW_EVENT_CONTRACT_FIELDS.TRUST));assert.deepEqual(d.eventAcceptanceOutcomes(),Object.values(WORKFLOW_EVENT_ACCEPTANCE_OUTCOMES));assert.ok(d.eventWaitFields().includes(WORKFLOW_EVENT_WAIT_FIELDS.RESUME));assert.ok(d.correlationCardinalities().includes(WORKFLOW_CORRELATION_CARDINALITIES.QUORUM));assert.ok(d.eventArrivalPolicies().includes(WORKFLOW_EVENT_ARRIVAL_POLICIES.OUT_OF_ORDER));});
test('ARCH-015-05 exposes durable timers, human decisions, and bounded agent interactions',()=>{const d=new WorkflowInteractionDescriptor();assert.deepEqual(d.timerTypes(),Object.values(WORKFLOW_TIMER_TYPES));assert.ok(d.timerFields().includes(WORKFLOW_TIMER_FIELDS.CALENDAR));assert.ok(d.timerMisfirePolicies().includes(WORKFLOW_TIMER_MISFIRE_POLICIES.BOUNDED_CATCH_UP));assert.ok(d.humanTaskStates().includes(WORKFLOW_HUMAN_TASK_STATES.CLARIFICATION));assert.ok(d.humanAssignmentTargets().includes(WORKFLOW_HUMAN_ASSIGNMENT_TARGETS.PROPERTY_OPERATOR));assert.ok(d.decisionContractFields().includes(WORKFLOW_DECISION_CONTRACT_FIELDS.DUTIES));assert.ok(d.multiPersonDecisions().includes(WORKFLOW_MULTI_PERSON_DECISIONS.DUAL_CONTROL));assert.ok(d.agentTaskTypes().includes(WORKFLOW_AGENT_TASK_TYPES.ACTION));assert.ok(d.agentResultFields().includes(WORKFLOW_AGENT_RESULT_FIELDS.UNCERTAINTY));});
test('ARCH-015-05 exposes operations, quality, rules, and boundaries',()=>{const d=new WorkflowInteractionDescriptor();assert.ok(d.operations().includes(WORKFLOW_INTERACTION_OPERATIONS.RECONCILE));assert.ok(d.qualityAttributes().includes(WORKFLOW_INTERACTION_QUALITY_ATTRIBUTES.ACCESSIBILITY));assert.ok(d.architecturalRules().includes(WORKFLOW_INTERACTION_RULES.SILENCE));assert.ok(d.architectureBoundaries().includes(WORKFLOW_INTERACTION_BOUNDARIES.SCHEDULER));});
test('ARCH-015-05 validates complete profiles and rejects interaction boundary violations',()=>{const d=new WorkflowInteractionDescriptor();assert.equal(d.validateProfile(complete(d)).isValid,true);const x=d.validateProfile({stableIdentities:false,versionedContracts:false,authenticatedAuthorizedSources:false,trustedTenantProperty:false,correlationNotAuthorization:false,activeWaitRequired:false,duplicateReplayHarmless:false,boundedArrivalPolicies:false,authoritativeOwnershipPreserved:false,durableTimers:false,explicitClockCalendarSemantics:false,distinctOccurrences:false,boundedMisfire:false,humanDecisionsAttributable:false,separationOfDuties:false,silenceNotApproval:false,decisionsImmutableWithCorrection:false,boundedAgentTasks:false,agentResultsValidated:false,deterministicRaceResolution:false,fullValidationBeforeResume:false,tenantPropertyIsolation:false,recoverableInteractions:false,privacyMinimized:false,vendorNeutral:false,technologyIndependent:false,endpointReceiptAdvancesState:true,correlationGrantsAuthority:true,globalOrderingAssumed:true,lateInputReopensTerminal:true,timerIsSleepingProcess:true,universalExactlyOnceTimer:true,notificationGrantsAuthority:true,freeTextControlsMaterialDecision:true,agentInfersAuthority:true,agentResultOwnsBusinessTruth:true,operatorForgesInteraction:true,untrustedScopeOverrides:true,selectsInfrastructure:true,definesAdjacentDetails:true});assert.equal(x.isValid,false);assert.match(x.errors.join('\n'),/must have a name/);assert.match(x.errors.join('\n'),/event-type/);assert.match(x.errors.join('\n'),/Silence must not be approval/);assert.match(x.errors.join('\n'),/must not advance workflow state/);});
test('ARCH-015-05 assertion detects incomplete interaction metadata',()=>{class Incomplete extends WorkflowInteractionDescriptor{timerFields(){return [];}}assert.throws(()=>new Incomplete().assertArchitecture(),e=>e instanceof PlatformError&&e.code===WORKFLOW_INTERACTION_ERROR_CODE&&e.details.errors.some(m=>m.includes('timerFields')));});
test('ARCH-015-05 profile is immutable and descriptor is registered',()=>{const d=addWorkflowEngine(new ServiceCollection()).buildServiceProvider().getRequiredService('WorkflowInteractionDescriptor');assert.ok(d instanceof WorkflowInteractionDescriptor);assert.equal(d.assertArchitecture().isValid,true);const p=complete(d);assert.ok(Object.isFrozen(p));assert.ok(Object.isFrozen(p.timerTypes));assert.throws(()=>p.timerTypes.push('x'),TypeError);});
function complete(d){const x={};for(const k of ['interactionTypes','eventContractFields','eventAcceptanceOutcomes','eventWaitFields','correlationCardinalities','eventArrivalPolicies','timerTypes','timerFields','timerMisfirePolicies','humanTaskStates','humanAssignmentTargets','decisionContractFields','multiPersonDecisions','agentTaskTypes','agentResultFields','operations','qualityAttributes','architecturalRules','architectureBoundaries'])x[k]=d[k]();return new WorkflowInteractionProfile({profileName:'Events Timers and Human Interaction',...x});}
