export * from './multi-tenancy-overview-constants.js';
export { MultiTenancyOverviewProfile } from './contracts/multi-tenancy-overview-profile.js';
export { MultiTenancyOverviewDescriptor } from './multi-tenancy-overview-descriptor.js';
export * from './tenant-domain-isolation-constants.js';
export { TenantDomainIsolationProfile } from './contracts/tenant-domain-isolation-profile.js';
export { TenantDomainIsolationDescriptor } from './tenant-domain-isolation/tenant-domain-isolation-descriptor.js';
export * from './tenant-lifecycle-provisioning-constants.js';
export { TenantLifecycleProvisioningProfile } from './contracts/tenant-lifecycle-provisioning-profile.js';
export { TenantLifecycleProvisioningDescriptor } from './tenant-lifecycle-provisioning/tenant-lifecycle-provisioning-descriptor.js';
export * from './identity-access-delegated-administration-constants.js';
export { IdentityAccessDelegatedAdministrationProfile } from './contracts/identity-access-delegated-administration-profile.js';
export { IdentityAccessDelegatedAdministrationDescriptor } from './identity-access-delegated-administration/identity-access-delegated-administration-descriptor.js';
export * from './data-isolation-residency-portability-constants.js';
export { DataIsolationResidencyPortabilityProfile } from './contracts/data-isolation-residency-portability-profile.js';
export { DataIsolationResidencyPortabilityDescriptor } from './data-isolation-residency-portability/data-isolation-residency-portability-descriptor.js';
export * from './configuration-entitlements-customization-constants.js';
export { ConfigurationEntitlementsCustomizationProfile } from './contracts/configuration-entitlements-customization-profile.js';
export { ConfigurationEntitlementsCustomizationDescriptor } from './configuration-entitlements-customization/configuration-entitlements-customization-descriptor.js';
export * from './tenant-aware-runtime-integration-constants.js';
export { TenantAwareRuntimeIntegrationProfile } from './contracts/tenant-aware-runtime-integration-profile.js';
export { TenantAwareRuntimeIntegrationDescriptor } from './tenant-aware-runtime-integration/tenant-aware-runtime-integration-descriptor.js';
export { addMultiTenancy } from './service-registration.js';
