export {
  ENTERPRISE_CONNECTIVITY_TARGETS,
  ENTERPRISE_INTEGRATION_MODEL_STAGES,
  FUTURE_INTEGRATION_OVERVIEW_DIRECTIONS,
  FUTURE_INTEGRATION_PRINCIPLE_DIRECTIONS,
  ASYNCHRONOUS_COMMUNICATION_BENEFITS,
  ENTERPRISE_INTEGRATION_PRINCIPLES,
  EVOLUTION_WITHOUT_DISRUPTION_REQUIREMENTS,
  HIGH_COHESION_BENEFITS,
  INTEGRATION_ARCHITECTURE_ERROR_CODES,
  INTEGRATION_BOUNDARY_SEPARATIONS,
  INTEGRATION_COMMUNICATION_MODELS,
  INTEGRATION_CONTRACT_ELEMENTS,
  INTEGRATION_CONTRACT_DEFINITION_ELEMENTS,
  INTEGRATION_DECISION_MODEL_STAGES,
  INTEGRATION_DOMAIN_NAMES,
  INTEGRATION_GOVERNANCE_FOUNDATIONS,
  INTEGRATION_LIFECYCLE_STAGES,
  INTEGRATION_OBJECTIVES,
  INTEGRATION_PARTICIPANT_TYPES,
  INTEGRATION_PRINCIPLE_GOVERNANCE_ACTIVITIES,
  INTEGRATION_PRINCIPLE_NAMES,
  INTEGRATION_PRINCIPLE_OBJECTIVES,
  INTEGRATION_PRINCIPLE_QUALITY_ATTRIBUTES,
  INTEGRATION_PRINCIPLE_SUPPORT_FACTORS,
  INTEGRATION_PRINCIPLES_RELATIONSHIP_FLOW_STAGES,
  INTEGRATION_QUALITY_ATTRIBUTES,
  INTEGRATION_RELIABILITY_CAPABILITIES,
  INTEGRATION_OBSERVABILITY_INFORMATION,
  INTEGRATION_RELATIONSHIP_FLOW_STAGES,
  INTEGRATION_SECURITY_REQUIREMENTS,
  INTEGRATION_TREATMENT_PRINCIPLES,
  LOOSE_COUPLING_AVOIDED_ASSUMPTIONS,
  PRINCIPLE_COMMUNICATION_STYLES,
  PRINCIPLE_LOOSE_COUPLING_AVOIDED_ASSUMPTIONS,
  PRINCIPLE_SECURITY_CONTROLS,
  STANDARDIZATION_BENEFITS,
  TECHNOLOGY_INDEPENDENCE_TARGETS,
  VERSION_COMPATIBILITY_REQUIREMENTS,
  INTEGRATION_OWNERSHIP_RESPONSIBILITIES
} from './constants.js';
export { IntegrationArchitectureValidationResult } from './contracts/integration-architecture-validation-result.js';
export { IntegrationContractBoundary } from './contracts/integration-contract-boundary.js';
export { IntegrationDecisionModel } from './contracts/integration-decision-model.js';
export { IntegrationDomainProfile } from './contracts/integration-domain-profile.js';
export { IntegrationPrincipleProfile } from './contracts/integration-principle-profile.js';
export { IntegrationOverviewDescriptor } from './overview/integration-overview-descriptor.js';
export { IntegrationPrinciplesDescriptor } from './principles/integration-principles-descriptor.js';
export { addIntegrationArchitecture } from './service-registration.js';
