import assert from 'node:assert/strict';
import test from 'node:test';
import { PlatformError, ServiceCollection } from '../../src/foundation/index.js';
import { MULTI_TENANCY_CAPABILITIES, MULTI_TENANCY_INVARIANTS, MULTI_TENANCY_ISOLATION_DIMENSIONS, MULTI_TENANCY_LIFECYCLE_STAGES, MULTI_TENANCY_OVERVIEW_ERROR_CODE, MULTI_TENANCY_REQUEST_STEPS, MultiTenancyOverviewDescriptor, MultiTenancyOverviewProfile, addMultiTenancy } from '../../src/multi-tenancy/index.js';

test('ARCH-018-01 exposes hierarchy, capability, isolation, and lifecycle metadata', () => { const descriptor = new MultiTenancyOverviewDescriptor(); assert.ok(descriptor.capabilities().includes(MULTI_TENANCY_CAPABILITIES.REGISTRY)); assert.ok(descriptor.invariants().includes(MULTI_TENANCY_INVARIANTS.FAIL_CLOSED)); assert.ok(descriptor.isolationDimensions().includes(MULTI_TENANCY_ISOLATION_DIMENSIONS.KNOWLEDGE)); assert.ok(descriptor.lifecycleStages().includes(MULTI_TENANCY_LIFECYCLE_STAGES.EXIT)); });
test('ARCH-018-01 exposes tenant-aware request, configuration, resource, and plane metadata', () => { const descriptor = new MultiTenancyOverviewDescriptor(); assert.ok(descriptor.requestSteps().includes(MULTI_TENANCY_REQUEST_STEPS.PROVIDER)); assert.ok(descriptor.configurationLevels().includes('mandatory-platform-controls')); assert.ok(descriptor.resourceFamilies().includes('agent-runs-tool-calls-and-model-consumption')); assert.ok(descriptor.planes().includes('tenant-control-plane')); });
test('ARCH-018-01 validates profiles and rejects tenancy shortcuts', () => { const descriptor = new MultiTenancyOverviewDescriptor(); assert.equal(descriptor.validateProfile(complete(descriptor)).isValid, true); const validation = descriptor.validateProfile({ explicitValidatedContext: false, providerOwnershipValidation: false, contextHeaderAuthority: true, gatewayOnlyEnforcement: true, aiAuthoritativeAccess: true, sharedResourcesUnbounded: true }); assert.equal(validation.isValid, false); assert.match(validation.errors.join('\n'), /explicit validated tenant context/); assert.match(validation.errors.join('\n'), /request headers/); assert.match(validation.errors.join('\n'), /gateway-only enforcement/); });
test('ARCH-018-01 detects incomplete overview metadata', () => { class IncompleteDescriptor extends MultiTenancyOverviewDescriptor { invariants() { return []; } } assert.throws(() => new IncompleteDescriptor().assertArchitecture(), (error) => error instanceof PlatformError && error.code === MULTI_TENANCY_OVERVIEW_ERROR_CODE); });
test('ARCH-018-01 profile is immutable and descriptor is registered', () => { const descriptor = addMultiTenancy(new ServiceCollection()).buildServiceProvider().getRequiredService('MultiTenancyOverviewDescriptor'); assert.ok(descriptor instanceof MultiTenancyOverviewDescriptor); assert.equal(descriptor.assertArchitecture().isValid, true); const profile = complete(descriptor); assert.ok(Object.isFrozen(profile)); assert.throws(() => profile.invariants.push('other'), TypeError); });
function complete(descriptor) { const metadata = {}; for (const key of ['objectives', 'stakeholders', 'scope', 'invariants', 'hierarchyLevels', 'capabilities', 'planes', 'isolationDimensions', 'isolationProfiles', 'lifecycleStages', 'requestSteps', 'configurationLevels', 'resourceFamilies', 'operatingRoles', 'architecturalRules', 'architectureBoundaries']) metadata[key] = descriptor[key](); return new MultiTenancyOverviewProfile({ profileName: 'Multi-Tenancy Overview', ...metadata }); }
