flowchart TB

Foundation

Experience

Gateway

Conversation

AI

Business

Data

Integration

Foundation --> Experience
Foundation --> Gateway
Foundation --> Conversation
Foundation --> AI
Foundation --> Business
Foundation --> Data
Foundation --> Integration

Experience --> Gateway

Gateway --> Conversation

Conversation --> AI

AI --> Business

Business --> Data

Business --> Integration